// Emit LogoData.cs and a standalone wwwroot SVG from sections.json.
const fs = require('fs');
const PROJ = 'C:/Users/colmr/CoachCubeColorPallette';
const { width: W, height: H, sections } = JSON.parse(fs.readFileSync('sections.json', 'utf8'));

for (const s of sections) {
  if (s.d.includes('"')) throw new Error(`path ${s.id} contains a quote`);
}

const cs = `// <auto-generated>
// Vector paths traced from SrcImage/CoachCube_Full_Logo_Navy.png.
// Each section is an independent path so its fill can be changed on its own.
// Regenerate with the tracer rather than hand-editing the path data.
// </auto-generated>

namespace CoachCubeColorPallette;

/// <summary>One independently recolourable region of the logo.</summary>
/// <param name="Id">Stable key used for selection and colour lookup.</param>
/// <param name="Name">Human readable label shown in the UI.</param>
/// <param name="DefaultColor">The colour this region has in the original artwork.</param>
/// <param name="D">SVG path data, in the <see cref="Width"/> x <see cref="Height"/> view box.</param>
public sealed record LogoSection(string Id, string Name, string DefaultColor, string D);

public static class LogoData
{
    public const int Width = ${W};
    public const int Height = ${H};

    /// <summary>Painting order: background first, so later sections draw on top of it.</summary>
    public static readonly IReadOnlyList<LogoSection> Sections =
    [
${sections.map(s => `        new("${s.id}", "${s.name}", "${s.color}", "${s.d}"),`).join('\n')}
    ];
}
`;
fs.writeFileSync(`${PROJ}/LogoData.cs`, cs);

const svg = [
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">`,
  ...sections.map(s => `  <path id="${s.id}" fill="${s.color}" fill-rule="evenodd" d="${s.d}"/>`),
  `</svg>`,
].join('\n');
fs.writeFileSync(`${PROJ}/wwwroot/coachcube-logo.svg`, svg);

console.log(`LogoData.cs: ${cs.length} chars, ${sections.length} sections`);
console.log(`wwwroot/coachcube-logo.svg: ${svg.length} chars`);
